# Backup
backup_path = ""

# Resource Manager
repository_path = ""
zotero_db_path = "" # path to zotero db
project_name = ""

# Schedule
timezone = "" # for example "America/Toronto"

# other
code_editor = ""
markdown_editor = ""
pdf_viewer = ""
