# Backup
backup_path = ""

# Resource Manager
repository_path = ""
zotero_db_path = "" # path to zotero db
file_explorer = "" # windows: explorer.exe / linux: nautilus
project_name = ""

# Schedule
timezone = "" # for example "America/Toronto"
todo_print_format = "" # short/long

# other
code_editor = ""
markdown_editor = ""
pdf_viewer = ""
